### ISSUE TITLE
DCGAN: adding a support for weights and biases logging

### ISSUE THREAD

**Issue by ishan121028** [ishan121028/UniTrain#26]

**Comment by mohityadaviitb** [comment]
import wandb
wandb.init(project='DCGAN', config={})

wandb.watch(disc.discriminator, log="all")


wandb.watch(gen.generator, log="all")
for epoch in range(num_epochs):
   
#26
wandb.log({'epoch': epoch, 'discriminator_loss': discriminator_loss, 'generator_loss': generator_loss})
