### ISSUE TITLE
TypeError: train_model() got an unexpected keyword argument 'num_epochs'

### ISSUE THREAD

**Issue by Mehul-Agrawal410** [ishan121028/UniTrain#34]
The DCGAN code given in the README.md passes keyword argument ``num_epochs`` to ``train_model`` while the actual argument in ``utils/DCGAN.py`` is ``epochs``

I can fix this if someone can confirm which one of the 2 should be changed

**Comment by ishan121028** [comment]
Yes @Mehul-Agrawal410 go ahead, I guess there was some mistake while making out the readme.md.

Also will review and merge your other commits by tomorrow.

**Comment by Mehul-Agrawal410** [comment]
which one should be changed? the one in README or train_model function?
