### ISSUE TITLE
NameError: name 'real_preds' is not defined. Did you mean: 'real_targets'?

### ISSUE THREAD

**Issue by Mehul-Agrawal410** [ishan121028/UniTrain#35]
in the ``train_discriminator`` function of ``utils/DCGAN.py``

**Comment by ishan121028** [comment]
@skillingshark @ahiliitb Can you look into this issue?

**Comment by ahiliitb** [comment]
Missing Line in utils.DCGAN.py
real_preds = discriminator(real_images)
just after line number 95
